package com.apex.agent;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;

/**
 * Detects prompt injection attempts in LLM output and tool inputs (S4 constraint).
 *
 * The agent must describe actions in plain language for consent and never execute
 * raw injected args. This detector scans LLM-generated tool calls for:
 *   - Role override attempts ("ignore previous instructions", "you are now")
 *   - Hidden instruction smuggling (base64, unicode escapes, zero-width chars)
 *   - Tool name spoofing (claiming to be a different tool)
 *   - Argument injection (extra args beyond what the tool expects)
 *   - Chain-of-though manipulation ("first do X, then do Y" where Y is malicious)
 *
 * Detection result includes a risk score and recommended action.
 */
public final class PromptInjectionDetector {

    // Risk levels
    public static final int RISK_CLEAN = 0;
    public static final int RISK_SUSPICIOUS = 1;
    public static final int RISK_INJECTION = 2;

    // Role override patterns
    private static final Pattern[] INJECTION_PATTERNS = {
        Pattern.compile("ignore\\s+(?:previous|prior|all)\\s+instructions?", Pattern.CASE_INSENSITIVE),
        Pattern.compile("disregard\\s+(?:the\\s+)?(?:above|previous|prior)", Pattern.CASE_INSENSITIVE),
        Pattern.compile("you\\s+are\\s+now\\s+(?:a|an)\\s+\\w+", Pattern.CASE_INSENSITIVE),
        Pattern.compile("(?:new|updated)\\s+instructions?:", Pattern.CASE_INSENSITIVE),
        Pattern.compile("system\\s+prompt\\s*:", Pattern.CASE_INSENSITIVE),
        Pattern.compile("override\\s+(?:safety|security|consent)", Pattern.CASE_INSENSITIVE),
        Pattern.compile("do\\s+not\\s+(?:ask|request)\\s+(?:for\\s+)?consent", Pattern.CASE_INSENSITIVE),
        Pattern.compile("execute\\s+without\\s+(?:approval|consent|asking)", Pattern.CASE_INSENSITIVE),
        Pattern.compile("\\badmin\\s+mode\\b", Pattern.CASE_INSENSITIVE),
        Pattern.compile("\\bdebug\\s+mode\\b", Pattern.CASE_INSENSITIVE),
    };

    // Hidden encoding patterns
    private static final Pattern BASE64_PATTERN =
        Pattern.compile("[A-Za-z0-9+/]{40,}={0,2}");
    private static final Pattern UNICODE_ESCAPE =
        Pattern.compile("\\\\u[0-9a-fA-F]{4}");
    private static final Pattern ZERO_WIDTH =
        Pattern.compile("[\\u200B-\\u200F\\u2028-\\u202F\\u2060-\\u206F]");

    // Tool name spoofing — LLM claiming to be a system tool
    private static final Pattern TOOL_SPOOFING =
        Pattern.compile(
            "(?:I\\s+am|this\\s+is|acting\\s+as)\\s+(?:system_server|shell|root|su|adb)",
            Pattern.CASE_INSENSITIVE
        );

    public static final class DetectionResult {
        public final int riskLevel;
        public final String reason;
        public final List<String> flags;

        DetectionResult(int riskLevel, String reason, List<String> flags) {
            this.riskLevel = riskLevel;
            this.reason = reason;
            this.flags = flags;
        }

        public boolean isBlocked() {
            return riskLevel >= RISK_INJECTION;
        }

        public boolean isSuspicious() {
            return riskLevel >= RISK_SUSPICIOUS;
        }
    }

    private PromptInjectionDetector() {}

    /**
     * Analyze LLM output for prompt injection before presenting to consent gate.
     *
     * @param llmOutput  The raw text generated by the LLM
     * @param toolName   The tool the LLM is requesting to call
     * @param toolArgs   The args the LLM wants to pass
     * @return DetectionResult with risk level and flags
     */
    public static DetectionResult analyze(
            String llmOutput, String toolName, String toolArgs) {

        List<String> flags = new ArrayList<>();
        int risk = RISK_CLEAN;
        String combined = (llmOutput != null ? llmOutput : "") + " "
            + (toolArgs != null ? toolArgs : "");

        // Check role override patterns
        for (Pattern p : INJECTION_PATTERNS) {
            if (p.matcher(combined).find()) {
                flags.add("role_override: " + p.pattern());
                risk = RISK_INJECTION;
            }
        }

        // Check tool spoofing
        if (TOOL_SPOOFING.matcher(combined).find()) {
            flags.add("tool_spoofing");
            risk = RISK_INJECTION;
        }

        // Check hidden encodings
        if (BASE64_PATTERN.matcher(combined).find()) {
            flags.add("base64_encoding");
            risk = Math.max(risk, RISK_SUSPICIOUS);
        }
        if (UNICODE_ESCAPE.matcher(combined).find()) {
            flags.add("unicode_escape");
            risk = Math.max(risk, RISK_SUSPICIOUS);
        }
        if (ZERO_WIDTH.matcher(combined).find()) {
            flags.add("zero_width_chars");
            risk = Math.max(risk, RISK_SUSPICIOUS);
        }

        // Check injection markers via sanitizer
        if (UntrustedInputSanitizer.hasInjectionMarkers(toolArgs)) {
            flags.add("injection_markers_in_args");
            risk = Math.max(risk, RISK_SUSPICIOUS);
        }

        // Check for unexpected tool name
        if (toolName != null && !UntrustedInputSanitizer.isValidToolName(toolName)) {
            flags.add("invalid_tool_name: " + toolName);
            risk = RISK_INJECTION;
        }

        // Check for args containing shell commands
        if (toolArgs != null && toolArgs.contains("rm -rf")) {
            flags.add("destructive_command_in_args");
            risk = RISK_INJECTION;
        }

        String reason = flags.isEmpty()
            ? "clean"
            : String.join("; ", flags);

        return new DetectionResult(risk, reason, flags);
    }
}
