// SPDX-License-Identifier: GPL-2.0-only
/*
 * drivers/apex/apex.c
 *
 * apex control plane (Redmi Note 12 4G, SM6225-AD)
 *
 * Provides:
 *   - /proc/apex/* read-only status surface (0444)
 *   - /proc/apex/policy write surface (0220, CAP_SYS_ADMIN required):
 *     "screen_off", "screen_on", "charge 0|1", "audio 0|1", "fg <uid>", "game 0|1"
 *   - /proc/apex/gaming read-write for gaming mode toggle (0644, CAP_SYS_ADMIN)
 *   - /proc/apex/governor read-only for tunable status
 *   - /proc/apex/wakealarm read-write (0644) for arming PMIC wake via epoch seconds
 *   - /proc/apex/version read-only for build version info
 *   - /proc/apex/stats read-only for cumulative statistics
 *   - automatic power_supply (charging) detection via notifier
 *   - battery status (capacity, health, temp) in /proc/apex/state
 *   - thermal zone monitoring with automatic CPU frequency capping
 *   - GPU devfreq control (screen_off/gaming modes)
 *   - 5-minute health tick (subsystem checks, logs to incident ring)
 *   - 7-day routine learner (moving average patterns for thermal/screen-off)
 *   - panic notifier: appends panic info to apex incident ring
 *   - RTC wakealarm: write epoch seconds to arm the PMIC wake
 *
 * Owns /proc/apex directory creation. Other apex modules (watchdog) must
 * use apex_get_proc_dir() to get the existing directory pointer rather than
 * calling proc_mkdir("apex", NULL) themselves.
 */

#define pr_fmt(fmt) KBUILD_MODNAME ": "

#include <linux/atomic.h>
#include <linux/capability.h>
#include <linux/cpufreq.h>
#include <linux/fs.h>
#include <linux/module.h>
#include <linux/notifier.h>
#include <linux/power_supply.h>
#include <linux/thermal.h>
#include <linux/devfreq.h>
#include <linux/slab.h>
#include <linux/jiffies.h>
#include <linux/delay.h>
#include <linux/kobject.h>
#include <linux/seq_file.h>
#include <linux/uidgid.h>
#include <linux/uaccess.h>
#include <linux/proc_fs.h>
#include <linux/workqueue.h>
#include <linux/suspend.h>
#include <linux/panic.h>
#include <linux/panic_notifier.h>
#include <linux/reboot.h>
#include <linux/rtc.h>
#include <linux/miscdevice.h>
#include <linux/rfkill.h>
#include <linux/mutex.h>

#include "apex_thermal_learner.h"

/* Build info — generated by build-kernel.sh or defaults */
#ifdef APEX_BUILD_VERSION
#define APEX_VERSION_STR APEX_BUILD_VERSION
#else
#define APEX_VERSION_STR "1.2.0"
#endif

#ifdef APEX_BUILD_DATE
#define APEX_BUILD_DATE_STR APEX_BUILD_DATE
#else
#define APEX_BUILD_DATE_STR __DATE__ " " __TIME__
#endif

#ifdef APEX_BUILD_GIT_HASH
#define APEX_GIT_STR APEX_BUILD_GIT_HASH
#else
#define APEX_GIT_STR "unknown"
#endif

/* Externs from other apex modules */
extern void apex_gov_set_screen_off(bool off);
extern void apex_gov_set_gaming(bool enable);
#ifdef CONFIG_APEX_CHARGE
extern void apex_charge_tick(void);
#endif

/* ---- constants/limits ---- */

#define APEX_INCIDENT_RING_SIZE	64
#define APEX_HEALTH_TICK_SEC	300
#define APEX_THERMAL_WARN_DEG	45
#define APEX_THERMAL_THROTTLE_DEG	55
#define APEX_THERMAL_CRITICAL_DEG	65
#define APEX_LEARNER_WINDOW_DAYS	7
#define APEX_LEARNER_TICKS		(APEX_LEARNER_WINDOW_DAYS * 24 * 60 * 12)

/* Thermal frequency cap percentages */
#define APEX_THERMAL_CAP_WARN_PCT	85
#define APEX_THERMAL_CAP_CRIT_PCT	70

/* ---- structures ---- */

enum apex_policy_row {
	APEX_ROW_IDLE,
	APEX_ROW_NORMAL,
	APEX_ROW_GAMING,
	APEX_ROW_SCREEN_OFF,
	APEX_ROW_COUNT
};

/* ---- Compiled 16-entry decision table ----
 * Indexed by (screen_on<<3)|(charging<<2)|(audio<<1)|(fg!=0)
 * Each entry maps to a policy row and specific actions.
 * Compiled at build, read-only, no policy file — per DESIGN.md §10.
 */
struct apex_decision_entry {
	enum apex_policy_row row;
	bool gpu_performance;		/* GPU governor = performance */
	bool gpu_powersave;		/* GPU governor = powersave */
	bool gov_gaming;		/* apex governor gaming mode */
	bool gov_screen_off;		/* apex governor screen-off mode */
	unsigned int sensor_rate_hz;	/* sensor rate cap */
	bool bt_scan_enabled;		/* BT scan allowed */
	bool wifi_multicast;		/* Wi-Fi multicast allowed */
};

#define APEX_DEC(screen, charge, audio, fg) \
	((screen << 3) | (charge << 2) | (audio << 1) | (fg))

static const struct apex_decision_entry apex_decision_table[16] = {
	/* idx 0: screen=0 charge=0 audio=0 fg=0 — idle, screen off */
	[APEX_DEC(0,0,0,0)] = {
		.row = APEX_ROW_SCREEN_OFF, .gpu_performance = false,
		.gpu_powersave = true, .gov_gaming = false, .gov_screen_off = true,
		.sensor_rate_hz = 10, .bt_scan_enabled = false, .wifi_multicast = false,
	},
	/* idx 1: screen=0 charge=0 audio=0 fg=1 — screen off, app in fg (rare) */
	[APEX_DEC(0,0,0,1)] = {
		.row = APEX_ROW_SCREEN_OFF, .gpu_performance = false,
		.gpu_powersave = true, .gov_gaming = false, .gov_screen_off = true,
		.sensor_rate_hz = 10, .bt_scan_enabled = false, .wifi_multicast = false,
	},
	/* idx 2: screen=0 charge=0 audio=1 fg=0 — screen off, audio playing */
	[APEX_DEC(0,0,1,0)] = {
		.row = APEX_ROW_SCREEN_OFF, .gpu_performance = false,
		.gpu_powersave = true, .gov_gaming = false, .gov_screen_off = true,
		.sensor_rate_hz = 10, .bt_scan_enabled = false, .wifi_multicast = false,
	},
	/* idx 3: screen=0 charge=0 audio=1 fg=1 — screen off, audio+app */
	[APEX_DEC(0,0,1,1)] = {
		.row = APEX_ROW_SCREEN_OFF, .gpu_performance = false,
		.gpu_powersave = true, .gov_gaming = false, .gov_screen_off = true,
		.sensor_rate_hz = 10, .bt_scan_enabled = false, .wifi_multicast = false,
	},
	/* idx 4: screen=0 charge=1 audio=0 fg=0 — charging, screen off */
	[APEX_DEC(0,1,0,0)] = {
		.row = APEX_ROW_SCREEN_OFF, .gpu_performance = false,
		.gpu_powersave = true, .gov_gaming = false, .gov_screen_off = true,
		.sensor_rate_hz = 10, .bt_scan_enabled = false, .wifi_multicast = false,
	},
	/* idx 5: screen=0 charge=1 audio=0 fg=1 — charging, screen off, app */
	[APEX_DEC(0,1,0,1)] = {
		.row = APEX_ROW_SCREEN_OFF, .gpu_performance = false,
		.gpu_powersave = true, .gov_gaming = false, .gov_screen_off = true,
		.sensor_rate_hz = 10, .bt_scan_enabled = false, .wifi_multicast = false,
	},
	/* idx 6: screen=0 charge=1 audio=1 fg=0 — charging, screen off, audio */
	[APEX_DEC(0,1,1,0)] = {
		.row = APEX_ROW_SCREEN_OFF, .gpu_performance = false,
		.gpu_powersave = true, .gov_gaming = false, .gov_screen_off = true,
		.sensor_rate_hz = 10, .bt_scan_enabled = false, .wifi_multicast = false,
	},
	/* idx 7: screen=0 charge=1 audio=1 fg=1 — charging, screen off, audio+app */
	[APEX_DEC(0,1,1,1)] = {
		.row = APEX_ROW_SCREEN_OFF, .gpu_performance = false,
		.gpu_powersave = true, .gov_gaming = false, .gov_screen_off = true,
		.sensor_rate_hz = 10, .bt_scan_enabled = false, .wifi_multicast = false,
	},
	/* idx 8: screen=1 charge=0 audio=0 fg=0 — screen on, idle/home */
	[APEX_DEC(1,0,0,0)] = {
		.row = APEX_ROW_IDLE, .gpu_performance = false,
		.gpu_powersave = false, .gov_gaming = false, .gov_screen_off = false,
		.sensor_rate_hz = 200, .bt_scan_enabled = true, .wifi_multicast = true,
	},
	/* idx 9: screen=1 charge=0 audio=0 fg=1 — screen on, app foreground */
	[APEX_DEC(1,0,0,1)] = {
		.row = APEX_ROW_NORMAL, .gpu_performance = false,
		.gpu_powersave = false, .gov_gaming = false, .gov_screen_off = false,
		.sensor_rate_hz = 200, .bt_scan_enabled = true, .wifi_multicast = true,
	},
	/* idx 10: screen=1 charge=0 audio=1 fg=0 — screen on, audio, home */
	[APEX_DEC(1,0,1,0)] = {
		.row = APEX_ROW_IDLE, .gpu_performance = false,
		.gpu_powersave = false, .gov_gaming = false, .gov_screen_off = false,
		.sensor_rate_hz = 200, .bt_scan_enabled = true, .wifi_multicast = true,
	},
	/* idx 11: screen=1 charge=0 audio=1 fg=1 — screen on, audio, app */
	[APEX_DEC(1,0,1,1)] = {
		.row = APEX_ROW_NORMAL, .gpu_performance = false,
		.gpu_powersave = false, .gov_gaming = false, .gov_screen_off = false,
		.sensor_rate_hz = 200, .bt_scan_enabled = true, .wifi_multicast = true,
	},
	/* idx 12: screen=1 charge=1 audio=0 fg=0 — charging, screen on, home */
	[APEX_DEC(1,1,0,0)] = {
		.row = APEX_ROW_IDLE, .gpu_performance = false,
		.gpu_powersave = false, .gov_gaming = false, .gov_screen_off = false,
		.sensor_rate_hz = 200, .bt_scan_enabled = true, .wifi_multicast = true,
	},
	/* idx 13: screen=1 charge=1 audio=0 fg=1 — charging, screen on, app */
	[APEX_DEC(1,1,0,1)] = {
		.row = APEX_ROW_NORMAL, .gpu_performance = false,
		.gpu_powersave = false, .gov_gaming = false, .gov_screen_off = false,
		.sensor_rate_hz = 200, .bt_scan_enabled = true, .wifi_multicast = true,
	},
	/* idx 14: screen=1 charge=1 audio=1 fg=0 — charging, screen on, audio, home */
	[APEX_DEC(1,1,1,0)] = {
		.row = APEX_ROW_IDLE, .gpu_performance = false,
		.gpu_powersave = false, .gov_gaming = false, .gov_screen_off = false,
		.sensor_rate_hz = 200, .bt_scan_enabled = true, .wifi_multicast = true,
	},
	/* idx 15: screen=1 charge=1 audio=1 fg=1 — charging, screen on, audio, app
	 * (gaming overrides this to APEX_ROW_GAMING via apex_determine_row) */
	[APEX_DEC(1,1,1,1)] = {
		.row = APEX_ROW_NORMAL, .gpu_performance = false,
		.gpu_powersave = false, .gov_gaming = false, .gov_screen_off = false,
		.sensor_rate_hz = 200, .bt_scan_enabled = true, .wifi_multicast = true,
	},
};

/* Compute the 4-bit decision index from current state */
static inline unsigned int apex_decision_index(void)
{
	return ((unsigned int)apex_state.screen_on << 3) |
	       ((unsigned int)apex_state.charging << 2) |
	       ((unsigned int)apex_state.audio_active << 1) |
	       ((unsigned int)(apex_state.foreground_uid != 0));
}

/* Get the current decision table entry (gaming overrides) */
static const struct apex_decision_entry *apex_current_decision(void)
{
	unsigned int idx = apex_decision_index();

	/* Gaming mode overrides everything — always use performance policy */
	if (apex_state.gaming_active) {
		static const struct apex_decision_entry gaming_entry = {
			.row = APEX_ROW_GAMING, .gpu_performance = true,
			.gpu_powersave = false, .gov_gaming = true,
			.gov_screen_off = false, .sensor_rate_hz = 200,
			.bt_scan_enabled = true, .wifi_multicast = true,
		};
		return &gaming_entry;
	}

	return &apex_decision_table[idx];
}

/* Per-policy thermal cap tracking */
struct apex_thermal_cap {
	unsigned int original_max;
	bool capped;
};

struct apex_state {
	bool screen_on;
	bool charging;
	bool audio_active;
	bool gaming_active;
	uid_t foreground_uid;

	/* thermal & power state */
	int current_temp;
	int thermal_throttle_level; /* 0: none, 1: warn, 2: throttle */
	bool gpu_boost_active;

	/* battery status */
	int battery_capacity;
	int battery_status; /* POWER_SUPPLY_STATUS_* */
	int battery_health;
	int battery_temp;

	/* GPU devfreq */
	struct devfreq *gpu_devfreq;
	char gpu_governor_default[32];

	/* routine learning — real 7-day thermal learner */
	struct apex_learner learner;

	/* incident ring */
	char *incidents[APEX_INCIDENT_RING_SIZE];
	unsigned int incident_count;
	unsigned int incident_head;
	spinlock_t incident_lock;

	/* health */
	unsigned int boot_count;
	unsigned long last_health_check;
	unsigned int recovery_attempts;

	/* wakealarm */
	unsigned long wakealarm_epoch;

	/* statistics */
	u64 total_policy_changes;
	u64 screen_on_time;
	u64 screen_off_time;
	u64 gaming_time;
	u64 thermal_events;
	u64 total_incidents;
	unsigned long last_screen_change;
	unsigned long last_gaming_change;

	/* thermal caps per policy */
	struct apex_thermal_cap thermal_caps[NUM_NCPUS];
};

static struct apex_state apex_state;
static struct proc_dir_entry *apex_proc_dir;
static struct delayed_work apex_health_work;
static struct notifier_block apex_psy_nb;

/* Mutex serializes policy state reads/writes across procfs, notifier,
 * health tick, and PM notifier contexts. The power_supply notifier
 * runs in process context (not atomic), so a mutex is safe. */
static DEFINE_MUTEX(apex_state_lock);

/* Local trim: strip trailing whitespace in-place (kernel-space version). */
static void apex_trim(char *s)
{
	size_t len = strlen(s);
	while (len > 0 && (s[len - 1] == '\n' || s[len - 1] == '\r' ||
	       s[len - 1] == ' ' || s[len - 1] == '\t'))
		s[--len] = '\0';
}

/* Export the proc_dir_entry so other apex modules (watchdog) can reuse it
 * instead of calling proc_mkdir("apex", NULL) which would return NULL. */
struct proc_dir_entry *apex_get_proc_dir(void)
{
	return apex_proc_dir;
}
EXPORT_SYMBOL_GPL(apex_get_proc_dir);

/* ---- incident ring helper ---- */

void apex_incident_log(const char *fmt, ...)
{
	va_list args;
	char buf[128];
	unsigned long flags;
	char *new_msg;

	va_start(args, fmt);
	vsnprintf(buf, sizeof(buf), fmt, args);
	va_end(args);

	spin_lock_irqsave(&apex_state.incident_lock, flags);

	/* kstrdup with GFP_ATOMIC can fail under memory pressure.
	 * If it does, preserve the existing message rather than
	 * overwriting the slot with NULL. */
	new_msg = kstrdup(buf, GFP_ATOMIC);
	if (new_msg) {
		kfree(apex_state.incidents[apex_state.incident_head]);
		apex_state.incidents[apex_state.incident_head] = new_msg;
		apex_state.incident_head = (apex_state.incident_head + 1) %
			APEX_INCIDENT_RING_SIZE;
		if (apex_state.incident_count < APEX_INCIDENT_RING_SIZE)
			apex_state.incident_count++;
		apex_state.total_incidents++;
	}

	spin_unlock_irqrestore(&apex_state.incident_lock, flags);
}
EXPORT_SYMBOL_GPL(apex_incident_log);

/* Export total incident count for watchdog minidump */
u64 apex_state_total_incidents(void)
{
	return apex_state.total_incidents;
}
EXPORT_SYMBOL_GPL(apex_state_total_incidents);

/* ---- GPU devfreq control ---- */

static void apex_gpu_devfreq_init(void)
{
	/* Try to find the GPU devfreq device by name */
	apex_state.gpu_devfreq = devfreq_get_devfreq_by_name("gpubw");
	if (!apex_state.gpu_devfreq)
		apex_state.gpu_devfreq = devfreq_get_devfreq_by_name(
			"1d00000.qcom,kgsl-3d0");

	if (apex_state.gpu_devfreq) {
		/* Save the default governor name */
		strscpy(apex_state.gpu_governor_default,
			apex_state.gpu_devfreq->governor_name,
			sizeof(apex_state.gpu_governor_default));
		pr_info("GPU devfreq found: %s\n",
			apex_state.gpu_governor_default);
	} else {
		pr_info("GPU devfreq not found — GPU control disabled\n");
	}
}

static void apex_gpu_set_governor(const char *gov)
{
	struct devfreq *df = apex_state.gpu_devfreq;
	int ret;

	if (!df || !df->governor)
		return;

	/* Switch the GPU devfreq governor by writing to the sysfs
	 * governor node. Direct struct manipulation is unsafe because
	 * devfreq_update_governor() reads df->governor_name to decide
	 * which governor to switch to — we must set the name first. */
	if (df->governor_name && strcmp(df->governor_name, gov) != 0) {
		/* Use the sysfs-equivalent: write governor name to
		 * /sys/class/devfreq/<dev>/governor via kernel API.
		 * devfreq_gov_set_target triggers a governor switch. */
		mutex_lock(&df->lock);
		/* Update the governor_name so devfreq_update_governor
		 * picks up the new one. */
		strscpy(df->governor_name, gov, sizeof(df->governor_name));
		ret = devfreq_update_governor(df);
		mutex_unlock(&df->lock);
		if (ret)
			apex_incident_log("GPU governor -> %s failed (%d)", gov, ret);
		else
			apex_incident_log("GPU governor -> %s", gov);
	}
}

static void apex_gpu_apply_policy(bool gaming, bool screen_off)
{
	if (!apex_state.gpu_devfreq)
		return;

	if (gaming)
		apex_gpu_set_governor("performance");
	else if (screen_off)
		apex_gpu_set_governor("powersave");
	else
		apex_gpu_set_governor(apex_state.gpu_governor_default);
}

/* ---- GPU min clock floor for gaming mode ----
 * During gaming, the Adreno 610 can drop to very low clocks during
 * brief idle moments, causing frame drops. Setting a min clock floor
 * at ~48% of max (600 MHz) prevents these drops.
 * From DroidRooter gaming optimization guide. */
#define APEX_GPU_MIN_FREQ_GAMING	"600000000"
#define APEX_GPU_MIN_FREQ_DEFAULT	"320000000"
#define APEX_GPU_MIN_FREQ_PATH		"/sys/class/kgsl/kgsl-3d0/devfreq/min_freq"

static void apex_gpu_set_min_freq(bool gaming)
{
	struct file *f;
	const char *freq;
	char buf[32];
	int len;

	f = filp_open(APEX_GPU_MIN_FREQ_PATH, O_WRONLY, 0);
	if (IS_ERR(f))
		return;

	freq = gaming ? APEX_GPU_MIN_FREQ_GAMING : APEX_GPU_MIN_FREQ_DEFAULT;
	len = snprintf(buf, sizeof(buf), "%s", freq);
	kernel_write(f, buf, len, &f->f_pos);
	filp_close(f, NULL);
}

/* ---- GPU bus/DDR DCVS scaling ----
 * The Adreno 610 is frequently memory-bandwidth-bound before it's
 * core-clock-bound. A bus-DCVS profile that tracks GPU load (not just
 * core clock) buys real frame-time consistency that a core-clock-only
 * tune misses.
 *
 * We scale the gpubw devfreq max_freq based on GPU load:
 * - High GPU load (>70%): allow full bus bandwidth
 * - Medium GPU load (30-70%): cap bus at 75% of max
 * - Low GPU load (<30%): cap bus at 50% of max (saves power at idle)
 *
 * The GPU load is read from /sys/class/kgsl/kgsl-3d0/devfreq/load
 * (format: "busy_time total_time"). */
#define APEX_GPU_LOAD_PATH		"/sys/class/kgsl/kgsl-3d0/devfreq/load"
#define APEX_GPU_BUS_MAX_PATH		"/sys/class/devfreq/gpubw/max_freq"
#define APEX_GPU_BUS_FULL		"7216000000"   /* full LPDDR4X bandwidth */
#define APEX_GPU_BUS_MID		"5412000000"   /* ~75% of max */
#define APEX_GPU_BUS_LOW		"3608000000"   /* ~50% of max */

static void apex_gpu_bus_dcvs_update(void)
{
	struct file *f;
	char buf[128];
	const char *bus_max;
	u64 busy, total;
	u32 load_pct;

	if (!apex_state.gpu_devfreq)
		return;

	/* Read GPU load */
	f = filp_open(APEX_GPU_LOAD_PATH, O_RDONLY, 0);
	if (IS_ERR(f))
		return;

	kernel_read(f, buf, sizeof(buf) - 1, &f->f_pos);
	filp_close(f, NULL);

	/* Parse "busy_time total_time" format */
	if (sscanf(buf, "%llu %llu", &busy, &total) != 2 || total == 0)
		return;

	load_pct = div64_u64(busy * 100, total);

	/* Select bus bandwidth based on GPU load */
	if (load_pct > 70)
		bus_max = APEX_GPU_BUS_FULL;
	else if (load_pct > 30)
		bus_max = APEX_GPU_BUS_MID;
	else
		bus_max = APEX_GPU_BUS_LOW;

	/* Write to gpubw devfreq max_freq */
	f = filp_open(APEX_GPU_BUS_MAX_PATH, O_WRONLY, 0);
	if (IS_ERR(f))
		return;

	kernel_write(f, bus_max, strlen(bus_max), &f->f_pos);
	filp_close(f, NULL);
}

/* ---- CPU cluster isolation for gaming mode ----
 * During gaming, isolate big cores (A73, cpu 0-3) for the foreground
 * game and push background tasks to little cluster (A53, cpu 4-7).
 * Reduces scheduling contention. From Ahnet-69/DroidRooter approach.
 *
 * We write cpuset configuration via kernel file I/O. The cpuset
 * paths are created by the Android init system. If they don't exist,
 * the writes silently fail (non-fatal). */
#define APEX_CPUSET_BG_PATH		"/dev/cpuset/background/cpus"
#define APEX_CPUSET_FG_PATH		"/dev/cpuset/foreground/cpus"
#define APEX_CPUSET_SYS_PATH		"/dev/cpuset/system/cpus"
#define APEX_CPUSET_RESTRICTED_PATH	"/dev/cpuset/restricted/cpus"

static void apex_cpuset_write(const char *path, const char *value)
{
	struct file *f;

	f = filp_open(path, O_WRONLY, 0);
	if (IS_ERR(f))
		return;
	kernel_write(f, value, strlen(value), &f->f_pos);
	filp_close(f, NULL);
}

static void apex_gaming_cpuset(bool gaming)
{
	if (gaming) {
		/* Push background to little cluster (A53, cpu 4-7) */
		apex_cpuset_write(APEX_CPUSET_BG_PATH, "4-7");
		/* Foreground gets big cluster (A73, cpu 0-3) */
		apex_cpuset_write(APEX_CPUSET_FG_PATH, "0-3");
		/* System stays on big cluster for responsiveness */
		apex_cpuset_write(APEX_CPUSET_SYS_PATH, "0-3");
		/* Restricted cgroup: big cluster only for perf-critical tasks */
		apex_cpuset_write(APEX_CPUSET_RESTRICTED_PATH, "0-3");
	} else {
		/* Restore default: all CPUs available to all cgroups */
		apex_cpuset_write(APEX_CPUSET_BG_PATH, "0-7");
		apex_cpuset_write(APEX_CPUSET_FG_PATH, "0-7");
		apex_cpuset_write(APEX_CPUSET_SYS_PATH, "0-7");
		apex_cpuset_write(APEX_CPUSET_RESTRICTED_PATH, "0-7");
	}
}

/* ---- thermal frequency cap ---- */

static void apex_thermal_apply_cap(int level)
{
	unsigned int cpu;
	unsigned int cap_pct;
	unsigned int new_max;

	if (level == 0)
		cap_pct = 100;
	else if (level == 1)
		cap_pct = APEX_THERMAL_CAP_WARN_PCT;
	else
		cap_pct = APEX_THERMAL_CAP_CRIT_PCT;

	for_each_possible_cpu(cpu) {
		struct cpufreq_policy *policy;
		struct apex_thermal_cap *cap = &apex_state.thermal_caps[cpu];

		policy = cpufreq_cpu_get(cpu);
		if (!policy)
			continue;

		if (!cap->capped && cap_pct < 100) {
			/* Save original max before capping */
			cap->original_max = policy->cpuinfo.max_freq;
			cap->capped = true;
		}

		if (cap_pct < 100 && cap->original_max > 0) {
			new_max = (cap->original_max * cap_pct) / 100;
			if (policy->max != new_max) {
				policy->max = new_max;
				cpufreq_update_policy(policy);
			}
		} else if (cap_pct == 100 && cap->capped) {
			/* Restore original max */
			if (cap->original_max > 0) {
				policy->max = cap->original_max;
				cpufreq_update_policy(policy);
			}
			cap->capped = false;
		}

		cpufreq_cpu_put(policy);
	}
}

/* ---- power_supply notifier (charging auto-detection) ---- */

static int apex_psy_notify(struct notifier_block *nb,
			   unsigned long event, void *data)
{
	struct power_supply *psy = data;

	if (event != PSY_EVENT_PROP_CHANGED)
		return NOTIFY_OK;

	if (!psy || !psy->desc || !psy->desc->name)
		return NOTIFY_OK;

	if (strcmp(psy->desc->name, "battery") != 0 &&
	    strcmp(psy->desc->name, "usb") != 0)
		return NOTIFY_OK;

	/* Read charging status from the battery power_supply */
	mutex_lock(&apex_state_lock);
	if (apex_state.battery_status == POWER_SUPPLY_STATUS_CHARGING ||
	    apex_state.battery_status == POWER_SUPPLY_STATUS_FULL) {
		if (!apex_state.charging) {
			apex_state.charging = true;
			apex_incident_log("charging started");
			mutex_unlock(&apex_state_lock);
			apex_apply_policy();
		} else {
			mutex_unlock(&apex_state_lock);
		}
	} else {
		if (apex_state.charging) {
			apex_state.charging = false;
			apex_incident_log("charging stopped");
			mutex_unlock(&apex_state_lock);
			apex_apply_policy();
		} else {
			mutex_unlock(&apex_state_lock);
		}
	}

	return NOTIFY_OK;
}

static void apex_battery_update(void)
{
	struct power_supply *psy;
	union power_supply_propval val;

	psy = power_supply_get_by_name("battery");
	if (!psy)
		return;

	mutex_lock(&apex_state_lock);

	if (!power_supply_get_property(psy, POWER_SUPPLY_PROP_CAPACITY, &val))
		apex_state.battery_capacity = val.intval;

	if (!power_supply_get_property(psy, POWER_SUPPLY_PROP_STATUS, &val)) {
		apex_state.battery_status = val.intval;
		/* Auto-detect charging state */
		if (val.intval == POWER_SUPPLY_STATUS_CHARGING ||
		    val.intval == POWER_SUPPLY_STATUS_FULL) {
			if (!apex_state.charging) {
				apex_state.charging = true;
				apex_incident_log("charging detected (battery)");
			}
		} else {
			if (apex_state.charging) {
				apex_state.charging = false;
				apex_incident_log("charging stopped (battery)");
			}
		}
	}

	if (!power_supply_get_property(psy, POWER_SUPPLY_PROP_HEALTH, &val))
		apex_state.battery_health = val.intval;

	if (!power_supply_get_property(psy, POWER_SUPPLY_PROP_TEMP, &val))
		apex_state.battery_temp = val.intval / 10; /* convert to C */

	mutex_unlock(&apex_state_lock);
	power_supply_put(psy);
}

/* ---- sensor rate cap via IIO sysfs ----
 * Writes the desired sensor rate cap to the IIO device sysfs.
 * On SM6225, the sensor HAL reads /sys/bus/iio/devices/iio:device*/sampling_frequency
 * or the vendor-specific rate control node. We write to the first
 * available IIO device's rate control. If the path doesn't exist,
 * the write silently fails (non-fatal — sensor control is best-effort). */
#define APEX_IIO_RATE_PATH	"/sys/bus/iio/devices/iio:device0/sampling_frequency"

static void apex_set_sensor_rate(unsigned int rate_hz)
{
	char buf[16];
	int len;
	struct file *f;

	if (rate_hz == 0)
		return;

	f = filp_open(APEX_IIO_RATE_PATH, O_WRONLY, 0);
	if (IS_ERR(f))
		return;

	len = snprintf(buf, sizeof(buf), "%u", rate_hz);
	kernel_write(f, buf, len, &f->f_pos);
	filp_close(f, NULL);
}

/* ---- BT scan policy via rfkill ----
 * When bt_scan_enabled is false, block BT via rfkill to prevent
 * background scanning. When true, unblock. Uses the rfkill API
 * already available in the kernel. */
static void apex_set_bt_scan(bool enabled)
{
	struct rfkill *rfk = rfkill_find(RFKILL_TYPE_BLUETOOTH);

	if (!rfk)
		return;

	if (!enabled)
		rfkill_set_block(rfk, true);
	else
		rfkill_set_block(rfk, false);

	rfkill_put(rfk);
}

/* ---- WiFi multicast policy ----
 * When wifi_multicast is false, we don't need to actively block it
 * (the framework handles multicast filtering). We log the policy
 * change for auditability. When true, no action needed — multicast
 * is allowed by default. */
static void apex_set_wifi_multicast(bool enabled)
{
	/* WiFi multicast filtering is handled by the framework's
	 * WifiManager.MulticastLock. The kernel decision table's
	 * wifi_multicast field is an advisory signal to userspace
	 * (readable via /proc/apex/policy_active) rather than a
	 * direct kernel action. We log the policy change. */
	if (!enabled)
		apex_incident_log("wifi multicast restricted (screen off)");
}

/* ---- policy determination engine ---- */

static enum apex_policy_row apex_determine_row(void)
{
	return apex_current_decision()->row;
}

static void apex_apply_policy(void)
{
	const struct apex_decision_entry *dec;
	enum apex_policy_row row;
	bool screen_off, gaming;
	unsigned long now;

	mutex_lock(&apex_state_lock);

	dec = apex_current_decision();
	row = dec->row;
	screen_off = dec->gov_screen_off;
	gaming = dec->gov_gaming;
	now = jiffies;

	/* Track statistics */
	apex_state.total_policy_changes++;

	/* Track screen time */
	if (apex_state.screen_on) {
		if (apex_state.last_screen_change > 0)
			apex_state.screen_on_time +=
				(now - apex_state.last_screen_change) / HZ;
	} else {
		if (apex_state.last_screen_change > 0)
			apex_state.screen_off_time +=
				(now - apex_state.last_screen_change) / HZ;
	}
	apex_state.last_screen_change = now;

	/* Track gaming time */
	if (gaming && apex_state.last_gaming_change > 0)
		apex_state.gaming_time +=
			(now - apex_state.last_gaming_change) / HZ;
	apex_state.last_gaming_change = gaming ? now : 0;

	/* 1. Sync governor state from decision table. */
	apex_gov_set_screen_off(screen_off);
	apex_gov_set_gaming(gaming);

	/* 2. Sync GPU devfreq from decision table. */
	if (dec->gpu_performance)
		apex_gpu_set_governor("performance");
	else if (dec->gpu_powersave)
		apex_gpu_set_governor("powersave");
	else
		apex_gpu_set_governor(apex_state.gpu_governor_default);

	/* 2b. GPU min clock floor: prevent frame drops during gaming. */
	apex_gpu_set_min_freq(gaming);

	/* 2c. CPU cluster isolation: big cores for foreground during gaming. */
	apex_gaming_cpuset(gaming);

	/* 2d. Apply sensor rate cap from decision table. */
	apex_set_sensor_rate(dec->sensor_rate_hz);

	/* 2e. Apply BT scan and WiFi multicast policy from decision table. */
	apex_set_bt_scan(dec->bt_scan_enabled);
	apex_set_wifi_multicast(dec->wifi_multicast);

	/* 3. Thermal frequency cap. */
	apex_thermal_apply_cap(apex_state.thermal_throttle_level);

	mutex_unlock(&apex_state_lock);
	(void)row;
}

/* ---- procfs implementation ---- */

static ssize_t apex_proc_policy_write(struct file *file, const char __user *user_buf,
				      size_t count, loff_t *ppos)
{
	char buf[64];
	size_t len = min(count, sizeof(buf) - 1);

	/* Only CAP_SYS_ADMIN (root) can modify kernel policy state */
	if (!capable(CAP_SYS_ADMIN))
		return -EPERM;

	if (copy_from_user(buf, user_buf, len))
		return -EFAULT;
	buf[len] = '\0';
	apex_trim(buf);

	mutex_lock(&apex_state_lock);

	/* Simple parser for "cmd arg" format. Use strcmp after trim
	 * to avoid prefix-matching "screen_offfoo" as "screen_off". */
	if (strcmp(buf, "screen_on") == 0) {
		apex_state.screen_on = true;
	} else if (strcmp(buf, "screen_off") == 0) {
		apex_state.screen_on = false;
	} else if (strncmp(buf, "charge ", 7) == 0) {
		apex_state.charging = (buf[7] == '1');
	} else if (strncmp(buf, "audio ", 6) == 0) {
		apex_state.audio_active = (buf[6] == '1');
	} else if (strncmp(buf, "fg ", 3) == 0) {
		apex_state.foreground_uid = (uid_t)simple_strtoul(buf + 3, NULL, 10);
	} else if (strncmp(buf, "game ", 5) == 0) {
		apex_state.gaming_active = (buf[5] == '1');
	} else {
		mutex_unlock(&apex_state_lock);
		return -EINVAL;
	}

	mutex_unlock(&apex_state_lock);
	apex_apply_policy();
	return len;
}

static ssize_t apex_proc_gaming_write(struct file *file, const char __user *user_buf,
				      size_t count, loff_t *ppos)
{
	char buf[8];
	size_t len = min(count, sizeof(buf) - 1);

	if (!capable(CAP_SYS_ADMIN))
		return -EPERM;

	if (copy_from_user(buf, user_buf, len))
		return -EFAULT;
	buf[len] = '\0';

	mutex_lock(&apex_state_lock);
	apex_state.gaming_active = (buf[0] == '1');
	mutex_unlock(&apex_state_lock);

	apex_apply_policy();
	return len;
}

static int apex_proc_status_show(struct seq_file *m, void *v)
{
	const char *bat_status = "unknown";

	switch (apex_state.battery_status) {
	case POWER_SUPPLY_STATUS_CHARGING: bat_status = "charging"; break;
	case POWER_SUPPLY_STATUS_DISCHARGING: bat_status = "discharging"; break;
	case POWER_SUPPLY_STATUS_FULL: bat_status = "full"; break;
	case POWER_SUPPLY_STATUS_NOT_CHARGING: bat_status = "not_charging"; break;
	default: bat_status = "unknown"; break;
	}

	seq_printf(m, "state: %s\n", apex_state.screen_on ? "on" : "off");
	seq_printf(m, "charging: %s\n", apex_state.charging ? "yes" : "no");
	seq_printf(m, "audio: %s\n", apex_state.audio_active ? "active" : "idle");
	seq_printf(m, "gaming: %s\n", apex_state.gaming_active ? "enabled" : "disabled");
	seq_printf(m, "foreground_uid: %u\n", apex_state.foreground_uid);
	seq_printf(m, "thermal_temp: %d C\n", apex_state.current_temp);
	seq_printf(m, "thermal_throttle: %d\n", apex_state.thermal_throttle_level);
	seq_printf(m, "battery_capacity: %d%%\n", apex_state.battery_capacity);
	seq_printf(m, "battery_status: %s\n", bat_status);
	seq_printf(m, "battery_temp: %d C\n", apex_state.battery_temp);
	seq_printf(m, "battery_health: %d\n", apex_state.battery_health);
	seq_printf(m, "boot_count: %u\n", apex_state.boot_count);
	return 0;
}

static int apex_proc_incidents_show(struct seq_file *m, void *v)
{
	unsigned int i;
	unsigned long flags;

	/* Use irqsave variant to match the writer — the writer may be
	 * called from interrupt context (panic notifier). */
	spin_lock_irqsave(&apex_state.incident_lock, flags);
	for (i = 0; i < apex_state.incident_count; i++) {
		unsigned int idx = (apex_state.incident_head + i) % APEX_INCIDENT_RING_SIZE;

		if (apex_state.incidents[idx])
			seq_printf(m, "[%u] %s\n", i, apex_state.incidents[idx]);
	}
	spin_unlock_irqrestore(&apex_state.incident_lock, flags);
	return 0;
}

static const struct proc_ops apex_policy_fops = {
	.proc_write = apex_proc_policy_write,
};

static const struct proc_ops apex_gaming_fops = {
	.proc_write = apex_proc_gaming_write,
};

static int apex_state_open(struct inode *inode, struct file *file)
{
	return single_open(file, apex_proc_status_show, NULL);
}

static const struct proc_ops apex_state_fops = {
	.proc_open = apex_state_open,
	.proc_read = seq_read,
	.proc_release = single_release,
};

static int apex_governor_show(struct seq_file *m, void *v)
{
	/* Read actual governor tunables from sysfs-equivalent values.
	 * Since we can't easily access the governor's internal dbs_data
	 * from here, we report what we know from the control plane. */
	seq_printf(m, "governor: apex\n");
	seq_printf(m, "screen_off: %s\n",
		   atomic_read(&apex_screen_off) ? "yes" : "no");
	seq_printf(m, "gaming: %s\n",
		   atomic_read(&apex_gaming) ? "yes" : "no");
	seq_printf(m, "thermal_level: %d\n", apex_state.thermal_throttle_level);
	seq_printf(m, "gpu_devfreq: %s\n",
		   apex_state.gpu_devfreq ? "available" : "unavailable");
	if (apex_state.gpu_devfreq)
		seq_printf(m, "gpu_governor: %s\n",
			   apex_state.gpu_devfreq->governor_name);
	return 0;
}

static int apex_governor_open(struct inode *inode, struct file *file)
{
	return single_open(file, apex_governor_show, NULL);
}

static const struct proc_ops apex_governor_fops = {
	.proc_open = apex_governor_open,
	.proc_read = seq_read,
	.proc_release = single_release,
};

static int apex_health_show(struct seq_file *m, void *v)
{
	seq_printf(m, "last_check: %lu\n", apex_state.last_health_check);
	seq_printf(m, "boot_count: %u\n", apex_state.boot_count);
	seq_printf(m, "recovery_attempts: %u\n", apex_state.recovery_attempts);
	seq_printf(m, "thermal_events: %llu\n", apex_state.thermal_events);
	return 0;
}

static int apex_health_open(struct inode *inode, struct file *file)
{
	return single_open(file, apex_health_show, NULL);
}

static const struct proc_ops apex_health_fops = {
	.proc_open = apex_health_open,
	.proc_read = seq_read,
	.proc_release = single_release,
};

/* ---- /proc/apex/version ---- */

static int apex_version_show(struct seq_file *m, void *v)
{
	seq_printf(m, "apex: %s\n", APEX_VERSION_STR);
	seq_printf(m, "build: %s\n", APEX_BUILD_DATE_STR);
	seq_printf(m, "git: %s\n", APEX_GIT_STR);
	seq_printf(m, "kernel: %s\n", UTS_RELEASE);
	seq_printf(m, "modules: apex governor, apex state, apex watchdog, "
		   "apex immortal, apex autoload\n");
	return 0;
}

static int apex_version_open(struct inode *inode, struct file *file)
{
	return single_open(file, apex_version_show, NULL);
}

static const struct proc_ops apex_version_fops = {
	.proc_open = apex_version_open,
	.proc_read = seq_read,
	.proc_release = single_release,
};

/* ---- /proc/apex/stats ---- */

static int apex_stats_show(struct seq_file *m, void *v)
{
	seq_printf(m, "total_policy_changes: %llu\n",
		   apex_state.total_policy_changes);
	seq_printf(m, "screen_on_time: %llu s\n",
		   apex_state.screen_on_time);
	seq_printf(m, "screen_off_time: %llu s\n",
		   apex_state.screen_off_time);
	seq_printf(m, "gaming_time: %llu s\n",
		   apex_state.gaming_time);
	seq_printf(m, "thermal_events: %llu\n",
		   apex_state.thermal_events);
	seq_printf(m, "total_incidents: %llu\n",
		   apex_state.total_incidents);
	return 0;
}

static int apex_stats_open(struct inode *inode, struct file *file)
{
	return single_open(file, apex_stats_show, NULL);
}

static const struct proc_ops apex_stats_fops = {
	.proc_open = apex_stats_open,
	.proc_read = seq_read,
	.proc_release = single_release,
};

/* ---- /proc/apex/thermal_profile ---- */

static int apex_thermal_profile_show(struct seq_file *m, void *v)
{
	apex_learner_show(m, &apex_state.learner);
	return 0;
}

static int apex_thermal_profile_open(struct inode *inode, struct file *file)
{
	return single_open(file, apex_thermal_profile_show, NULL);
}

static const struct proc_ops apex_thermal_profile_fops = {
	.proc_open = apex_thermal_profile_open,
	.proc_read = seq_read,
	.proc_release = single_release,
};

/* ---- /proc/apex/policy_active ---- */

static int apex_policy_active_show(struct seq_file *m, void *v)
{
	enum apex_policy_row row = apex_determine_row();
	const char *row_names[APEX_ROW_COUNT] = {
		"idle", "normal", "gaming", "screen_off"
	};
	unsigned int idx = ((unsigned int)apex_state.screen_on << 3) |
			   ((unsigned int)apex_state.charging << 2) |
			   ((unsigned int)apex_state.audio_active << 1) |
			   ((unsigned int)(apex_state.foreground_uid != 0));

	seq_printf(m, "row: %s\n", row_names[row]);
	seq_printf(m, "decision_index: %u (screen=%d charge=%d audio=%d fg=%d)\n",
		   idx, apex_state.screen_on, apex_state.charging,
		   apex_state.audio_active,
		   apex_state.foreground_uid != 0);
	return 0;
}

static int apex_policy_active_open(struct inode *inode, struct file *file)
{
	return single_open(file, apex_policy_active_show, NULL);
}

static const struct proc_ops apex_policy_active_fops = {
	.proc_open = apex_policy_active_open,
	.proc_read = seq_read,
	.proc_release = single_release,
};

/* ---- /proc/apex/bt_status ---- */

static int apex_bt_status_show(struct seq_file *m, void *v)
{
	/* Read BT rfkill state if available */
	struct rfkill *rfk = rfkill_find(RFKILL_TYPE_BLUETOOTH);

	if (rfk) {
		bool blocked = rfkill_blocked(rfk);
		seq_printf(m, "rfkill_blocked: %s\n", blocked ? "yes" : "no");
		rfkill_put(rfk);
	} else {
		seq_printf(m, "rfkill_blocked: unavailable\n");
	}
	return 0;
}

static int apex_bt_status_open(struct inode *inode, struct file *file)
{
	return single_open(file, apex_bt_status_show, NULL);
}

static const struct proc_ops apex_bt_status_fops = {
	.proc_open = apex_bt_status_open,
	.proc_read = seq_read,
	.proc_release = single_release,
};

/* ---- /proc/apex/sensor_status ---- */

static int apex_sensor_status_show(struct seq_file *m, void *v)
{
	const struct apex_decision_entry *dec;
	struct path p;
	int device_count = 0;

	/* Enumerate IIO devices by counting subdirectories */
	if (kern_path("/sys/bus/iio/devices", LOOKUP_FOLLOW, &p) == 0) {
		path_put(&p);
		seq_printf(m, "iio_bus: available\n");
	} else {
		seq_printf(m, "iio_bus: unavailable\n");
	}

	/* Report current sensor rate from the active decision table entry */
	dec = apex_current_decision();
	seq_printf(m, "current_rate_cap: %u Hz\n", dec->sensor_rate_hz);
	seq_printf(m, "bt_scan: %s\n", dec->bt_scan_enabled ? "enabled" : "disabled");
	seq_printf(m, "wifi_multicast: %s\n", dec->wifi_multicast ? "enabled" : "disabled");
	seq_printf(m, "current_screen: %s\n",
		   apex_state.screen_on ? "on" : "off");
	return 0;
}

static int apex_sensor_status_open(struct inode *inode, struct file *file)
{
	return single_open(file, apex_sensor_status_show, NULL);
}

static const struct proc_ops apex_sensor_status_fops = {
	.proc_open = apex_sensor_status_open,
	.proc_read = seq_read,
	.proc_release = single_release,
};

/* ---- /proc/apex/modules ---- */

static int apex_modules_show(struct seq_file *m, void *v)
{
	/* List loaded kernel modules, filtering for apex/pentest-related ones */
	struct module *mod;

	mutex_lock(&module_mutex);
	list_for_each_entry(mod, &modules, list) {
		if (strstr(mod->name, "apex") ||
		    strstr(mod->name, "ath9k") ||
		    strstr(mod->name, "carl9170") ||
		    strstr(mod->name, "rt2x00") ||
		    strstr(mod->name, "rtl8") ||
		    strstr(mod->name, "dvb_usb") ||
		    strstr(mod->name, "nfc") ||
		    strstr(mod->name, "can") ||
		    strstr(mod->name, "usb_serial") ||
		    strstr(mod->name, "hid") ||
		    strstr(mod->name, "netfilter"))
			seq_printf(m, "%s %u\n", mod->name,
				   mod->init_layout.size);
	}
	mutex_unlock(&module_mutex);
	return 0;
}

static int apex_modules_open(struct inode *inode, struct file *file)
{
	return single_open(file, apex_modules_show, NULL);
}

static const struct proc_ops apex_modules_fops = {
	.proc_open = apex_modules_open,
	.proc_read = seq_read,
	.proc_release = single_release,
};

/* ---- /dev/nh_ctl — pentest control misc device ---- */

static ssize_t nh_ctl_write(struct file *file, const char __user *user_buf,
			    size_t count, loff_t *ppos)
{
	char buf[256];
	size_t len = min(count, sizeof(buf) - 1);

	if (!capable(CAP_SYS_ADMIN))
		return -EPERM;

	if (copy_from_user(buf, user_buf, len))
		return -EFAULT;
	buf[len] = '\0';

	/* Parse commands: "monitor on|off", "load <module>", "unload <module> */
	if (strncmp(buf, "monitor ", 8) == 0) {
		char *arg = buf + 8;
		apex_trim(arg);

		if (strncmp(arg, "on", 2) == 0) {
			/* Request monitor mode module loading */
			request_module("ath9k_htc");
			request_module("carl9170");
			apex_incident_log("nh_ctl: monitor mode requested (modules loading)");
		} else if (strncmp(arg, "off", 3) == 0) {
			apex_incident_log("nh_ctl: monitor mode off");
		} else {
			return -EINVAL;
		}
	} else if (strncmp(buf, "load ", 5) == 0) {
		char *mod_name = buf + 5;
		int ret;

		/* Trim newline */
		len = strlen(mod_name);
		while (len > 0 && (mod_name[len-1] == '\n' || mod_name[len-1] == '\r'))
			mod_name[--len] = '\0';

		/* Whitelist allowed module names — prevent arbitrary module loading */
		static const char * const allowed_modules[] = {
			"ath9k_htc", "carl9170", "rtl8187", "rtl8x2bu",
			"8812au", "8814au", "8188eu", "88x2bu",
			"mt7610u", "mt7612u", "dvb_usb_rtl28xxu",
			"hackrf", "airspy", "gs_usb", "peak_usb",
			"ch341", "cp210x", "ftdi_sio", "pl2303",
			"btusb", "ath10k_sdio",
		};
		bool allowed = false;
		size_t mi;
		for (mi = 0; mi < ARRAY_SIZE(allowed_modules); mi++) {
			if (strcmp(mod_name, allowed_modules[mi]) == 0) {
				allowed = true;
				break;
			}
		}
		if (!allowed) {
			apex_incident_log("nh_ctl: rejected load %s (not whitelisted)", mod_name);
			return -EPERM;
		}

		ret = request_module("%s", mod_name);
		if (ret)
			apex_incident_log("nh_ctl: load %s failed (%d)", mod_name, ret);
		else
			apex_incident_log("nh_ctl: loaded %s", mod_name);
	} else if (strncmp(buf, "unload ", 7) == 0) {
		char *mod_name = buf + 7;

		len = strlen(mod_name);
		while (len > 0 && (mod_name[len-1] == '\n' || mod_name[len-1] == '\r'))
			mod_name[--len] = '\0';

		/* We can't directly unload modules from here safely,
		 * but we can log the request for userspace to handle */
		apex_incident_log("nh_ctl: unload requested for %s", mod_name);
	} else {
		return -EINVAL;
	}

	return count;
}

static const struct file_operations nh_ctl_fops = {
	.owner = THIS_MODULE,
	.write = nh_ctl_write,
};

static struct miscdevice nh_ctl_dev = {
	.minor = MISC_DYNAMIC_MINOR,
	.name = "nh_ctl",
	.fops = &nh_ctl_fops,
	.mode = 0220,
};

/* ---- wakealarm: read-write for arming PMIC wake ---- */

static int apex_wakealarm_show(struct seq_file *m, void *v)
{
	seq_printf(m, "%lu\n", apex_state.wakealarm_epoch);
	return 0;
}

static ssize_t apex_wakealarm_write(struct file *file, const char __user *user_buf,
				    size_t count, loff_t *ppos)
{
	char buf[32];
	size_t len = min(count, sizeof(buf) - 1);
	unsigned long epoch;
	int ret;

	if (!capable(CAP_SYS_ADMIN))
		return -EPERM;

	if (copy_from_user(buf, user_buf, len))
		return -EFAULT;
	buf[len] = '\0';

	ret = kstrtoul(strim(buf), 10, &epoch);
	if (ret)
		return ret;

	apex_state.wakealarm_epoch = epoch;

	/* Arm the RTC wakealarm via sysfs if available.
	 * The class RTC interface at /sys/class/rtc/rtc0/wakealarm
	 * accepts epoch seconds. We try it and log if it fails. */
	{
		struct file *f;

		f = filp_open("/sys/class/rtc/rtc0/wakealarm", O_WRONLY, 0);
		if (!IS_ERR(f)) {
			char alarm_buf[32];
			int alarm_len;

			/* "+<seconds>" means relative to current time.
			 * Writing absolute epoch requires the RTC to support it.
			 * We write the absolute epoch value. */
			alarm_len = snprintf(alarm_buf, sizeof(alarm_buf),
					     "%lu", epoch);
			kernel_write(f, alarm_buf, alarm_len, &f->f_pos);
			filp_close(f, NULL);
		}
	}

	apex_incident_log("wakealarm armed: epoch %lu", epoch);
	return len;
}

static int apex_wakealarm_open(struct inode *inode, struct file *file)
{
	return single_open(file, apex_wakealarm_show, NULL);
}

static const struct proc_ops apex_wakealarm_fops = {
	.proc_open = apex_wakealarm_open,
	.proc_read = seq_read,
	.proc_write = apex_wakealarm_write,
	.proc_release = single_release,
};

static int apex_incidents_open(struct inode *inode, struct file *file)
{
	return single_open(file, apex_proc_incidents_show, NULL);
}

static const struct proc_ops apex_incidents_fops = {
	.proc_open = apex_incidents_open,
	.proc_read = seq_read,
	.proc_release = single_release,
};

/* ---- health tick & automation ---- */

static void apex_health_tick(struct work_struct *work)
{
	struct thermal_zone_device *tz;
	int temp = 0;
	int prev_level;

	/* 1. Thermal check */
	mutex_lock(&apex_state_lock);
	tz = thermal_zone_get_zone_by_name("cpu-therm");
	if (!tz)
		tz = thermal_zone_get_zone_by_name("soc");

	if (tz && thermal_zone_get_temp(tz, &temp) == 0) {
		apex_state.current_temp = temp / 1000;
		prev_level = apex_state.thermal_throttle_level;

		/* Use learner-adjusted trip points if available, else defaults */
		int warn_deg = apex_state.learner.trips.warn_deg;
		int throttle_deg = apex_state.learner.trips.throttle_deg;
		int critical_deg = apex_state.learner.trips.critical_deg;

		if (apex_state.current_temp >= critical_deg) {
			apex_state.thermal_throttle_level = 2;
			if (prev_level < 2) {
				apex_incident_log("thermal critical: %d C (trip=%d)",
						  apex_state.current_temp, critical_deg);
				apex_state.thermal_events++;
			}
		} else if (apex_state.current_temp >= throttle_deg) {
			apex_state.thermal_throttle_level = 1;
			if (prev_level < 1) {
				apex_incident_log("thermal throttle: %d C (trip=%d)",
						  apex_state.current_temp, throttle_deg);
				apex_state.thermal_events++;
			}
		} else {
			if (prev_level > 0)
				apex_incident_log("thermal normal: %d C",
						  apex_state.current_temp);
			apex_state.thermal_throttle_level = 0;
		}
	}
	mutex_unlock(&apex_state_lock);
	/* Accumulate thermal sample for the 7-day learner.	 * This runs regardless of whether a thermal zone was found —
	 * if no zone is available, we use the last known temperature
	 * (or 0 if never set) so the learner still collects data. */
	{
		int big_freq = 0, little_freq = 0;
		struct cpufreq_policy *pol;
		unsigned int cpu;

		/* Read big cluster (cpu 0) and little cluster (cpu 4) freqs */
		for_each_possible_cpu(cpu) {
			pol = cpufreq_cpu_get(cpu);
			if (pol) {
				if (cpu < 4)
					big_freq = pol->cur;
				else
					little_freq = pol->cur;
				cpufreq_cpu_put(pol);
			}
			if (big_freq > 0 && little_freq > 0)
				break;
		}

		apex_learner_add_sample(&apex_state.learner,
					apex_state.current_temp,
					big_freq, little_freq,
					apex_state.foreground_uid);
	}

	/* 2. Update battery status */
	apex_battery_update();

	/* 3. Update health timestamp */
	mutex_lock(&apex_state_lock);
	apex_state.last_health_check = jiffies;
	mutex_unlock(&apex_state_lock);

	/* 4. Learner: 7-day thermal profile is updated per-sample
	 *    in apex_learner_add_sample() above. Trip point
	 *    adjustment happens automatically after 7 days. */

	/* 5. Re-apply policy based on new state */
	apex_apply_policy();

	/* 5b. GPU bus/DDR DCVS: scale bus bandwidth based on GPU load.
	 * The Adreno 610 is memory-bandwidth-bound before core-clock-bound,
	 * so tracking GPU load for bus scaling gives better frame-time
	 * consistency than core-clock-only tuning. */
	apex_gpu_bus_dcvs_update();

	/* 5c. Charge manager tick: run JEITA-aware thermal mitigation,
	 * charge limit enforcement, and SoH tracking. The charge manager
	 * reads battery temp/voltage/current from the power_supply class
	 * and applies ICC stepping via the PM7250B SMB5 charger driver. */
#ifdef CONFIG_APEX_CHARGE
	apex_charge_tick();
#endif

	/* 6. Schedule next tick (5 minutes) */
	schedule_delayed_work(&apex_health_work, APEX_HEALTH_TICK_SEC * HZ);
}

/* ---- PM and panic notifiers ---- */

static int apex_pm_notify(struct notifier_block *nb, unsigned long action,
			  void *data)
{
	switch (action) {
	case PM_SUSPEND_PREPARE:
		mutex_lock(&apex_state_lock);
		apex_state.screen_on = false;
		mutex_unlock(&apex_state_lock);
		apex_apply_policy();
		break;
	case PM_POST_SUSPEND:
		mutex_lock(&apex_state_lock);
		apex_state.screen_on = true;
		mutex_unlock(&apex_state_lock);
		apex_apply_policy();
		break;
	}
	return NOTIFY_OK;
}

static struct notifier_block apex_pm_nb = {
	.notifier_call = apex_pm_notify,
	.priority = 0,
};

static int apex_panic_notify(struct notifier_block *nb, unsigned long action,
			     void *data)
{
	const char *msg = data ? (const char *)data : "unknown";

	apex_incident_log("kernel panic: %s", msg);
	return NOTIFY_OK;
}

static struct notifier_block apex_panic_nb = {
	.notifier_call = apex_panic_notify,
	.priority = 0,
};

/* ---- driver init/exit ---- */

static int __init apex_init(void)
{
	memset(&apex_state, 0, sizeof(apex_state));
	/* boot_count: future persistence via /proc/cmdline or vendor sysfs.
	 * For now, default to 1. */
	apex_state.boot_count = 1;
	apex_state.battery_capacity = -1;
	apex_state.battery_temp = -1;
	spin_lock_init(&apex_state.incident_lock);

	/* Initialize 7-day thermal learner (loads from persist if available) */
	apex_learner_init(&apex_state.learner);

	/* Create /proc/apex/ directory — this module owns it.
	 * Other apex modules use apex_get_proc_dir() to get the pointer. */
	apex_proc_dir = proc_mkdir("apex", NULL);
	if (!apex_proc_dir)
		return -ENOMEM;

	/* Create proc nodes */
	proc_create("state", 0444, apex_proc_dir, &apex_state_fops);
	proc_create("policy", 0220, apex_proc_dir, &apex_policy_fops);
	proc_create("gaming", 0644, apex_proc_dir, &apex_gaming_fops);
	proc_create("governor", 0444, apex_proc_dir, &apex_governor_fops);
	proc_create("incidents", 0444, apex_proc_dir, &apex_incidents_fops);
	proc_create("health", 0444, apex_proc_dir, &apex_health_fops);
	proc_create("wakealarm", 0644, apex_proc_dir, &apex_wakealarm_fops);
	proc_create("version", 0444, apex_proc_dir, &apex_version_fops);
	proc_create("stats", 0444, apex_proc_dir, &apex_stats_fops);
	proc_create("thermal_profile", 0444, apex_proc_dir, &apex_thermal_profile_fops);
	proc_create("policy_active", 0444, apex_proc_dir, &apex_policy_active_fops);
	proc_create("bt_status", 0444, apex_proc_dir, &apex_bt_status_fops);
	proc_create("sensor_status", 0444, apex_proc_dir, &apex_sensor_status_fops);
	proc_create("modules", 0444, apex_proc_dir, &apex_modules_fops);

	/* Register /dev/nh_ctl pentest control misc device */
	misc_register(&nh_ctl_dev);

	/* Initialize GPU devfreq control */
	apex_gpu_devfreq_init();

	/* Register notifiers */
	register_pm_notifier(&apex_pm_nb);
	atomic_notifier_chain_register(&panic_notifier_list, &apex_panic_nb);

	/* Register power_supply notifier for charging auto-detection */
	apex_psy_nb.notifier_call = apex_psy_notify;
	power_supply_reg_notifier(&apex_psy_nb);

	/* Start health tick (5 minutes) */
	INIT_DELAYED_WORK(&apex_health_work, apex_health_tick);
	schedule_delayed_work(&apex_health_work, APEX_HEALTH_TICK_SEC * HZ);

	/* Initial battery read */
	apex_battery_update();

	apex_apply_policy();
	pr_info("apex control plane v%s ready (boot %u)\n",
		APEX_VERSION_STR, apex_state.boot_count);
	return 0;
}

static void __exit apex_exit(void)
{
	int i;
	unsigned long flags;

	cancel_delayed_work_sync(&apex_health_work);
	atomic_notifier_chain_unregister(&panic_notifier_list, &apex_panic_nb);
	unregister_pm_notifier(&apex_pm_nb);
	power_supply_unreg_notifier(&apex_psy_nb);

	/* Restore thermal caps */
	apex_thermal_apply_cap(0);

	/* Free incident ring */
	spin_lock_irqsave(&apex_state.incident_lock, flags);
	for (i = 0; i < APEX_INCIDENT_RING_SIZE; i++)
		kfree(apex_state.incidents[i]);
	spin_unlock_irqrestore(&apex_state.incident_lock, flags);

	/* Remove proc entries — this removes the entire /proc/apex/ tree.
	 * The watchdog module must remove its own entry before this runs
	 * (link order guarantees apex.ko loads before apex_watchdog.ko
	 * and unloads after). */

	/* Deregister /dev/nh_ctl */
	misc_deregister(&nh_ctl_dev);

	/* Persist learner state before unloading */
	apex_learner_save(&apex_state.learner);

	if (apex_proc_dir)
		proc_remove(apex_proc_dir);
}

module_init(apex_init);
module_exit(apex_exit);

MODULE_LICENSE("GPL v2");
MODULE_DESCRIPTION("Apex Control Plane v" APEX_VERSION_STR);
