#!/system/bin/sh
# apex_configure_susfs.sh — device-side configuration for the susfs4ksu-module
# (sidex15/susfs4ksu-module). Generates every persistent config file the module
# reads at boot:
#
#   /data/adb/susfs4ksu/config.sh            module toggles (hide_cusrom, ...)
#   /data/adb/susfs4ksu/sus_path.txt         explicit sus_path entries
#   /data/adb/susfs4ksu/kernelversion.txt    uname -r to report (spoof_uname=2)
#   /data/adb/VerifiedBootHash/VerifiedBootHash.txt  ro.boot.vbmeta.digest value
#
# Idempotent — safe to re-run after every ROM/kernel update (files are
# rewritten from the values below).
#
# Kernel requirement: SUSFS >= 1.5.2 with set_proc_cmdline support
# (Zepharo R9 ships SUSFS 2.2.0; APEX >= the SPOOF_CMDLINE port).
#
# Usage: run as root (adb shell su -c sh /data/adb/apex/configure_susfs.sh)

set -eu

PERSISTENT_DIR="/data/adb/susfs4ksu"

# ── Editable values ──────────────────────────────────────────────────────

# Real TEE boot hash — copy from Native Detector / Key Attestation ("Boot hash").
# Must match the attestation value; never invent one.
BOOT_HASH="102ae65d6eee19a6f5624ed88d9d87375391e763340d378b2c6f316d8ef11da5"

# uname -r reported to apps (spoof_uname=2). Set to the stock kernel string of
# the ROM's fingerprint for a consistent narrative, or leave empty to disable.
KERNEL_RELEASE=""

# Extra sus_path entries (one per line, no leading/trailing spaces).
# /data/app dirs of the KSU manager + HMA + LSPosed manager protect against
# raw directory scans that PackageManager hooks cannot hide.
EXTRA_SUS_PATHS="
#/data/app/com.rifsxd.ksunext
#/data/app/com.tsng.hidemyapplist
#/data/app/org.lsposed.manager
"

# ── Module toggles ───────────────────────────────────────────────────────

# hide_cusrom: sus_path every path matching lineage/crdroid on /system, /vendor,
# /system_ext, /product. This is the broad kill for the smaps/maps/file/package
# detections. Wiki warns of possible instability on some ROMs — if apps crash,
# set to 0 and rely on sus_path.txt below.
HIDE_CUSROM=1

# spoof_cmdline: /proc/cmdline -> androidboot.verifiedbootstate=green.
# Requires kernel set_proc_cmdline (R9 SUSFS 2.2.0 / APEX port).
SPOOF_CMDLINE=1

# Strip 'lineage' strings from vendor_sepolicy.cil / compatibility_matrix.device.xml
# (mounts a cleaned copy + sus_kstat spoofs stat).
HIDE_VENDOR_SEPOLICY=1
HIDE_COMPAT_MATRIX=1

# hide_loops hides KSU module.img loops under /proc/fs/jbd2|ext4 — leave OFF on
# KernelSU-Next / OverlayFS per the module wiki.
HIDE_LOOPS=0

# sus_su replaces /system/bin/su with the sus_su driver (kernel-gated su).
SUS_SU=1

# spoof_uname: 0=off, 1=boot-completed, 2=post-fs-data (earliest).
SPOOF_UNAME=2

# force_hide_lsposed: only for legacy LSPosed dex2oat mounts — leave OFF for
# LSPosed-Next / JingMatrix (wiki).
FORCE_HIDE_LSPOSED=0

SUSFS_LOG=1

# ── Write config.sh ──────────────────────────────────────────────────────

mkdir -p "$PERSISTENT_DIR"
cat > "$PERSISTENT_DIR/config.sh" <<EOF
# Generated by apex_configure_susfs.sh — re-run that script to regenerate.
hide_cusrom=$HIDE_CUSROM
hide_gapps=0
hide_revanced=0
spoof_uname=$SPOOF_UNAME
spoof_cmdline=$SPOOF_CMDLINE
hide_vendor_sepolicy=$HIDE_VENDOR_SEPOLICY
hide_compat_matrix=$HIDE_COMPAT_MATRIX
hide_loops=$HIDE_LOOPS
sus_su=$SUS_SU
sus_su_active=$SUS_SU
force_hide_lsposed=$FORCE_HIDE_LSPOSED
susfs_log=$SUSFS_LOG
EOF

# ── Write sus_path.txt (read by the module's post-mount.sh) ──────────────

cat > "$PERSISTENT_DIR/sus_path.txt" <<EOF
# Explicit sus_path entries (one per line, '#' = comment).
# post-mount.sh applies these via: ksu_susfs add_sus_path <path>
#
# LineageOS framework resource APK + its compiled vdex (smaps/maps/stat reads).
/system/framework/org.lineageos.platform-res.apk
/system/framework/oat/arm64/org.lineageos.platform.vdex
#
# Custom ROM markers.
/system/addon.d
/system/bin/install-recovery.sh
/vendor/bin/install-recovery.sh
#
# Hidden tool apps (raw /data/app scans).
${EXTRA_SUS_PATHS}
EOF

# ── Write VerifiedBootHash (service.sh resets ro.boot.vbmeta.digest from it) ──

mkdir -p /data/adb/VerifiedBootHash
printf '%s\n' "$BOOT_HASH" > /data/adb/VerifiedBootHash/VerifiedBootHash.txt

# ── Write kernelversion.txt (used when spoof_uname=2) ────────────────────

if [ -n "$KERNEL_RELEASE" ]; then
    printf '%s\n' "$KERNEL_RELEASE" > "$PERSISTENT_DIR/kernelversion.txt"
else
    rm -f "$PERSISTENT_DIR/kernelversion.txt"
fi

echo "susfs config written to $PERSISTENT_DIR"
echo "  config.sh            -> hide_cusrom=$HIDE_CUSROM spoof_cmdline=$SPOOF_CMDLINE"
echo "  sus_path.txt         -> $(grep -cv '^#\|^$' "$PERSISTENT_DIR/sus_path.txt") entries"
echo "  VerifiedBootHash     -> $BOOT_HASH"
if [ -n "$KERNEL_RELEASE" ]; then
    echo "  kernelversion.txt    -> $KERNEL_RELEASE"
fi
echo
echo "Reboot for changes to take effect (module reads these at boot)."
echo "If HIDE_CUSROM=1 causes app crashes, set it to 0 and re-run."
exit 0
