#!/usr/bin/env bash
# tools/build-kernel.sh — build the apex kernel for Redmi Note 12 4G (topaz)
#
# Usage: ./build-kernel.sh [defconfig] [variant] [--clean] [--dry-run]
#                              [--modules] [--version] [--profile <name>]
#   defconfig: chickernel_defconfig (default) or khaje-stock_defconfig
#   variant:   none (default), ksun, ksun.susfs
#   --profile: battery, balanced (default), performance
#   --clean:   force full rebuild (default: incremental)
#   --dry-run: show what would be done without executing
#   --modules: only build modules (skip Image)
#   --version: print version info and exit
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APEX="$(cd "$HERE/.." && pwd)"
KERNEL="$APEX/kernel"
OUT="$APEX/out"

DEFCONFIG="chickernel_defconfig"
VARIANT=""
PROFILE="balanced"
DO_CLEAN=0
DRY_RUN=0
MODULES_ONLY=0
SHOW_VERSION=0

# Parse args
while [ $# -gt 0 ]; do
  case "$1" in
    --clean) DO_CLEAN=1 ;;
    --dry-run) DRY_RUN=1 ;;
    --modules) MODULES_ONLY=1 ;;
    --version) SHOW_VERSION=1 ;;
    --profile) shift; PROFILE="${1:-balanced}" ;;
    battery|balanced|performance) PROFILE="$1" ;;
    ksun|ksun.susfs) VARIANT="$1" ;;
    *_defconfig) DEFCONFIG="$1" ;;
  esac
  shift
done

# --- Version info ---
APEX_VERSION="1.2.0"
GIT_HASH="$(cd "$APEX" 2>/dev/null && git rev-parse --short HEAD 2>/dev/null || echo 'unknown')"
BUILD_DATE="$(date '+%Y-%m-%d %H:%M:%S')"

if [ "$SHOW_VERSION" -eq 1 ]; then
  echo "apex kernel build system v$APEX_VERSION"
  echo "  git:     $GIT_HASH"
  echo "  date:    $BUILD_DATE"
  echo "  target:  Redmi Note 12 4G (topaz/tapas)"
  echo "  kernel:  Linux 5.15.211 (CAF bengal-5.15)"
  exit 0
fi

JOBS=$(nproc)

# --- Toolchain dependency checks ---
# Supports: system clang (default), Neutron Clang (via --neutron or NEUTRON_CLANG env)
check_toolchain() {
  local missing=0
  local tools=(
    "clang"
    "ld.lld"
    "llvm-ar"
    "llvm-nm"
    "llvm-objcopy"
    "llvm-objdump"
    "llvm-strip"
    "aarch64-linux-gnu-gcc"
  )
  for tool in "${tools[@]}"; do
    if ! command -v "$tool" >/dev/null 2>&1; then
      echo "  ERROR: required tool not found: $tool" >&2
      missing=$((missing + 1))
    fi
  done
  if [ "$missing" -gt 0 ]; then
    echo "  $missing tool(s) missing. Install clang/llvm and aarch64-linux-gnu-gcc." >&2
    echo "  Or set NEUTRON_CLANG=/path/to/neutron/clang/bin" >&2
    exit 1
  fi
}

# Neutron Clang support (actively maintained, LTO + PGO + BOLT + Polly)
if [ -n "${NEUTRON_CLANG:-}" ] && [ -d "${NEUTRON_CLANG}/bin" ]; then
  export PATH="${NEUTRON_CLANG}/bin:$PATH"
  echo "  Using Neutron Clang: ${NEUTRON_CLANG}/bin"
fi

echo "=== APEX kernel build v$APEX_VERSION ==="
echo "  defconfig: $DEFCONFIG"
echo "  variant:   ${VARIANT:-none}"
echo "  profile:   $PROFILE"
echo "  jobs:      $JOBS"
echo "  kernel:    $KERNEL"
echo "  out:       $OUT"
echo "  clean:     $DO_CLEAN"
echo "  modules:   $MODULES_ONLY"
echo "  dry-run:   $DRY_RUN"
echo "  git:       $GIT_HASH"
echo ""

if [ "$DRY_RUN" -eq 0 ]; then
  check_toolchain
fi

[ -d "$KERNEL" ] || {
  echo "kernel tree not found: $KERNEL" >&2
  exit 1
}

# Timer helper
phase_start=0
phase_name=""
start_phase() {
  phase_name="$1"
  phase_start=$SECONDS
  if [ "$DRY_RUN" -eq 1 ]; then
    echo ">>> [DRY RUN] $phase_name"
  else
    echo ">>> $phase_name"
  fi
}
end_phase() {
  local elapsed=$((SECONDS - phase_start))
  echo "    ($phase_name: ${elapsed}s)"
}

# 0. Generate build-info.h
start_phase "Generating build-info.h"
if [ "$DRY_RUN" -eq 0 ]; then
  BUILD_INFO_DIR="$APEX/patches/apex-state/src"
  mkdir -p "$BUILD_INFO_DIR"
  cat > "$BUILD_INFO_DIR/build-info.h" << EOF
/* Auto-generated by build-kernel.sh — do not edit */
#define APEX_BUILD_VERSION "$APEX_VERSION"
#define APEX_BUILD_GIT_HASH "$GIT_HASH"
#define APEX_BUILD_DATE "$BUILD_DATE"
EOF
fi
end_phase

# 1. Clean output directory
start_phase "Cleaning output directory"
if [ "$DRY_RUN" -eq 0 ]; then
  if [ "$DO_CLEAN" -eq 1 ] || [ ! -d "$OUT" ]; then
    rm -rf "$OUT"
    mkdir -p "$OUT"
  else
    echo "    (incremental build — use --clean for full rebuild)"
  fi
fi
end_phase

# 2. Apply all patches (failures are fatal)
start_phase "Applying apex patches"
if [ "$DRY_RUN" -eq 0 ]; then
  PATCH_FAILURES=0
  for patch_dir in "$APEX"/patches/apex-*; do
    [ -d "$patch_dir" ] || continue
    if [ -f "$patch_dir/apply.sh" ]; then
      echo "  applying: $(basename "$patch_dir")"
      if ! bash "$patch_dir/apply.sh" "$KERNEL"; then
        echo "  ERROR: $(basename "$patch_dir") apply failed!" >&2
        PATCH_FAILURES=$((PATCH_FAILURES + 1))
      fi
    fi
  done

  if [ -d "$APEX/patches/device-backports" ] && [ -f "$APEX/patches/device-backports/apply.sh" ]; then
    echo "  applying: device-backports"
    if ! bash "$APEX/patches/device-backports/apply.sh" "$KERNEL"; then
      echo "  ERROR: device-backports apply failed!" >&2
      PATCH_FAILURES=$((PATCH_FAILURES + 1))
    fi
  fi

  if [ "$PATCH_FAILURES" -gt 0 ]; then
    echo ">>> $PATCH_FAILURES patch(es) failed. Aborting build." >&2
    echo "    (Patches may already be applied — re-run with --clean if you" >&2
    echo "     want to start from a fresh kernel tree.)" >&2
    exit 1
  fi
fi
end_phase

# 3. Merge defconfig fragments
start_phase "Merging defconfig fragments"
FRAGMENTS=""
for frag in "$APEX"/defconfig/*.config; do
  [ -f "$frag" ] || continue
  FRAGMENTS="$FRAGMENTS $frag"
done

if [ -n "$VARIANT" ] && [ -f "$KERNEL/arch/arm64/configs/chickernel-variants/$VARIANT.config" ]; then
  FRAGMENTS="$FRAGMENTS $KERNEL/arch/arm64/configs/chickernel-variants/$VARIANT.config"
fi

# 3b. Add profile-specific defconfig fragment
PROFILE_FRAG="$APEX/defconfig/profile-${PROFILE}.config"
if [ -f "$PROFILE_FRAG" ]; then
  FRAGMENTS="$FRAGMENTS $PROFILE_FRAG"
  echo "  profile fragment: $PROFILE_FRAG"
else
  echo "  WARNING: profile fragment not found: $PROFILE_FRAG" >&2
fi
end_phase

# 4. Configure
start_phase "Configuring kernel"
if [ "$DRY_RUN" -eq 0 ]; then
  cd "$KERNEL"
  make O="$OUT" ARCH=arm64 "$DEFCONFIG"

  if [ -n "$FRAGMENTS" ]; then
    ./scripts/kconfig/merge_config.sh -m -r -O "$OUT" \
      "$OUT/.config" $FRAGMENTS
    make O="$OUT" ARCH=arm64 olddefconfig </dev/null
  fi
fi
end_phase

# 5. Build
start_phase "Building kernel"
if [ "$DRY_RUN" -eq 0 ]; then
  # KCFLAGS: -march=armv8.4-a needed because KHAJE uses armv8.2-a but kernel
  # inline asm uses ARMv8.4 TLBI range instructions. clang's integrated
  # assembler uses the compiler's -march for inline asm, not -Wa,-march.
  # -Wno-error downgrades remaining clang 22 diagnostics to warnings.
  if [ "$MODULES_ONLY" -eq 1 ]; then
    echo "  (modules only — skipping Image)"
    make O="$OUT" ARCH=arm64 -j"$JOBS" \
      CROSS_COMPILE=aarch64-linux-gnu- \
      CROSS_COMPILE_COMPAT=aarch64-linux-gnu- \
      CC=clang \
      AR=llvm-ar \
      NM=llvm-nm \
      OBJCOPY=llvm-objcopy \
      OBJDUMP=llvm-objdump \
      STRIP=llvm-strip \
      LD=ld.lld \
      AS=aarch64-linux-gnu- \
      KCFLAGS="-march=armv8.4-a+crc+sha2+aes -Wno-error" \
      modules
  else
    make O="$OUT" ARCH=arm64 -j"$JOBS" W=1 \
      CROSS_COMPILE=aarch64-linux-gnu- \
      CROSS_COMPILE_COMPAT=aarch64-linux-gnu- \
      CC=clang \
      AR=llvm-ar \
      NM=llvm-nm \
      OBJCOPY=llvm-objcopy \
      OBJDUMP=llvm-objdump \
      STRIP=llvm-strip \
      LD=ld.lld \
      AS=aarch64-linux-gnu- \
      KCFLAGS="-march=armv8.4-a+crc+sha2+aes -Wno-error"
  fi
fi
end_phase

# 6. Verify output
if [ "$DRY_RUN" -eq 0 ] && [ "$MODULES_ONLY" -eq 0 ]; then
  KERNEL_IMAGE="$OUT/arch/arm64/boot/Image"

  if [ -f "$KERNEL_IMAGE" ]; then
    echo ""
    echo "=== Build successful ==="
    echo "  Image: $KERNEL_IMAGE ($(du -h "$KERNEL_IMAGE" | cut -f1))"
    ls -la "$OUT"/arch/arm64/boot/dts/qcom/*.dtb 2>/dev/null | head -5
    echo ""
    echo "  Modules:"
    find "$OUT" -name "*.ko" | head -20
    echo ""

    # 6b. Compile SELinux policy
    start_phase "Compiling SELinux policy"
    if [ -x "$APEX/tools/compile-selinux.sh" ]; then
      "$APEX/tools/compile-selinux.sh"
    fi
    end_phase

    echo "  Next: ./tools/verify.sh && ./tools/package-anykernel3.sh"
  else
    echo "=== Build FAILED ==="
    exit 1
  fi
elif [ "$DRY_RUN" -eq 1 ]; then
  echo ""
  echo "=== Dry run complete ==="
  echo "  (No files were modified or built)"
elif [ "$MODULES_ONLY" -eq 1 ]; then
  echo ""
  echo "=== Module build complete ==="
  echo "  Modules:"
  find "$OUT" -name "*.ko" | head -20
fi
